# Generated by Django 5.2.14 on 2026-06-04 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_status_flow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupportRequest',
        ),
    ]
